name = "sheer"
compatibility_date = "2024-02-24"

[site]
bucket = "./dist"

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
name = "sheer-production"

[env.staging]
name = "sheer-staging"
