name: Push to Hugging Face Space

on:
  push:
    branches:
      - gh-pages  # Set to your default branch if different
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  push-to-huggingface:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE }}  # Format: username/space-name
        run: |
          echo "Pushing to Hugging Face Space: ${HF_SPACE}"
          
          # Set URL with token for authentication
          git remote add space https://api-key:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}
          
          # Push to the gh-pages branch of the Space
          git push --force space gh-pages:gh-pages