name: Push to Hugging Face Space

on:
  # Trigger after GitHub Pages deployment succeeds
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  push-to-huggingface:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Configure Git for Hugging Face
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Create temporary branch for HF deployment
        run: |
          # Create and switch to a new branch with just the dist contents
          git checkout --orphan temp-branch
          git rm -rf .
          cp -r dist/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy to Hugging Face Space"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE }}  # Format: username/space-name
        run: |
          echo "Pushing to Hugging Face Space: ${HF_SPACE}"
          
          # Set URL with token for authentication
          git remote add space https://api-key:${HF_TOKEN}@huggingface.co/spaces/${HF_SPACE}
          
          # Push to the main branch of the Space
          git push --force space temp-branch:main